//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var string: string { .init(bundle: bundle, preferredLanguages: nil, locale: nil) }
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var info: info { .init(bundle: bundle) }
  var entitlements: entitlements { .init() }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var reuseIdentifier: reuseIdentifier { .init() }
  var storyboard: storyboard { .init(bundle: bundle) }

  func string(bundle: Foundation.Bundle) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: nil)
  }
  func string(locale: Foundation.Locale) -> string {
    .init(bundle: bundle, preferredLanguages: nil, locale: locale)
  }
  func string(preferredLanguages: [String], locale: Locale? = nil) -> string {
    .init(bundle: bundle, preferredLanguages: preferredLanguages, locale: locale)
  }
  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func info(bundle: Foundation.Bundle) -> info {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.string` struct is generated, and contains static references to 2 localization tables.
  struct string {
    let bundle: Foundation.Bundle
    let preferredLanguages: [String]?
    let locale: Locale?
    var localizable: localizable { .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale)) }
    var localizables: localizables { .init(source: .init(bundle: bundle, tableName: "Localizables", preferredLanguages: preferredLanguages, locale: locale)) }

    func localizable(preferredLanguages: [String]) -> localizable {
      .init(source: .init(bundle: bundle, tableName: "Localizable", preferredLanguages: preferredLanguages, locale: locale))
    }
    func localizables(preferredLanguages: [String]) -> localizables {
      .init(source: .init(bundle: bundle, tableName: "Localizables", preferredLanguages: preferredLanguages, locale: locale))
    }


    /// This `_R.string.localizable` struct is generated, and contains static references to 10 localization keys.
    struct localizable {
      let source: RswiftResources.StringResource.Source

      /// en translation: Bug Report
      ///
      /// Key: Bug Report
      ///
      /// Locales: en, zh-Hans
      var bugReport: RswiftResources.StringResource { .init(key: "Bug Report", tableName: "Localizable", source: source, developmentValue: "Bug Report", comment: nil) }

      /// en translation: Console Log
      ///
      /// Key: Console Log
      ///
      /// Locales: en, zh-Hans
      var consoleLog: RswiftResources.StringResource { .init(key: "Console Log", tableName: "Localizable", source: source, developmentValue: "Console Log", comment: nil) }

      /// en translation: Dismiss
      ///
      /// Key: Dismiss
      ///
      /// Locales: en, zh-Hans
      var dismiss: RswiftResources.StringResource { .init(key: "Dismiss", tableName: "Localizable", source: source, developmentValue: "Dismiss", comment: nil) }

      /// en translation: Done
      ///
      /// Key: Done
      ///
      /// Locales: en, zh-Hans
      var done: RswiftResources.StringResource { .init(key: "Done", tableName: "Localizable", source: source, developmentValue: "Done", comment: nil) }

      /// en translation: Include Console Log
      ///
      /// Key: Include Console Log
      ///
      /// Locales: en, zh-Hans
      var includeConsoleLog: RswiftResources.StringResource { .init(key: "Include Console Log", tableName: "Localizable", source: source, developmentValue: "Include Console Log", comment: nil) }

      /// en translation: Report
      ///
      /// Key: Report
      ///
      /// Locales: en, zh-Hans
      var report: RswiftResources.StringResource { .init(key: "Report", tableName: "Localizable", source: source, developmentValue: "Report", comment: nil) }

      /// en translation: Report a Bug
      ///
      /// Key: Report a Bug
      ///
      /// Locales: en, zh-Hans
      var reportABug: RswiftResources.StringResource { .init(key: "Report a Bug", tableName: "Localizable", source: source, developmentValue: "Report a Bug", comment: nil) }

      /// en translation: Select Screenshot…
      ///
      /// Key: Select Screenshot…
      ///
      /// Locales: en, zh-Hans
      var selectScreenshot: RswiftResources.StringResource { .init(key: "Select Screenshot…", tableName: "Localizable", source: source, developmentValue: "Select Screenshot…", comment: nil) }

      /// en translation: Send
      ///
      /// Key: Send
      ///
      /// Locales: en, zh-Hans
      var send: RswiftResources.StringResource { .init(key: "Send", tableName: "Localizable", source: source, developmentValue: "Send", comment: nil) }

      /// en translation: Tap the screenshot to annotate.
      ///
      /// Key: Tap the screenshot to annotate.
      ///
      /// Locales: en, zh-Hans
      var tapTheScreenshotToAnnotate: RswiftResources.StringResource { .init(key: "Tap the screenshot to annotate.", tableName: "Localizable", source: source, developmentValue: "Tap the screenshot to annotate.", comment: nil) }
    }

    /// This `_R.string.localizables` struct is generated, and contains static references to 22 localization keys.
    struct localizables {
      let source: RswiftResources.StringResource.Source

      /// en translation: Feedback
      ///
      /// Key: feedBackCopy
      ///
      /// Locales: en
      var feedBackCopy: RswiftResources.StringResource { .init(key: "feedBackCopy", tableName: "Localizables", source: source, developmentValue: "Feedback", comment: nil) }

      /// en translation: Your email address
      ///
      /// Key: feedBackEmailTitle
      ///
      /// Locales: en
      var feedBackEmailTitle: RswiftResources.StringResource { .init(key: "feedBackEmailTitle", tableName: "Localizables", source: source, developmentValue: "Your email address", comment: nil) }

      /// en translation: Help us contact you
      ///
      /// Key: feedBackHelpUsCopy
      ///
      /// Locales: en
      var feedBackHelpUsCopy: RswiftResources.StringResource { .init(key: "feedBackHelpUsCopy", tableName: "Localizables", source: source, developmentValue: "Help us contact you", comment: nil) }

      /// en translation: WE’D LOVE TO HEAR FROM YOU
      ///
      /// Key: feedBackHintCopy
      ///
      /// Locales: en
      var feedBackHintCopy: RswiftResources.StringResource { .init(key: "feedBackHintCopy", tableName: "Localizables", source: source, developmentValue: "WE’D LOVE TO HEAR FROM YOU", comment: nil) }

      /// en translation: Fitness content
      ///
      /// Key: feedBackIssuesRadio1
      ///
      /// Locales: en
      var feedBackIssuesRadio1: RswiftResources.StringResource { .init(key: "feedBackIssuesRadio1", tableName: "Localizables", source: source, developmentValue: "Fitness content", comment: nil) }

      /// en translation: Workout difficulty
      ///
      /// Key: feedBackIssuesRadio2
      ///
      /// Locales: en
      var feedBackIssuesRadio2: RswiftResources.StringResource { .init(key: "feedBackIssuesRadio2", tableName: "Localizables", source: source, developmentValue: "Workout difficulty", comment: nil) }

      /// en translation: Subscription
      ///
      /// Key: feedBackIssuesRadio3
      ///
      /// Locales: en
      var feedBackIssuesRadio3: RswiftResources.StringResource { .init(key: "feedBackIssuesRadio3", tableName: "Localizables", source: source, developmentValue: "Subscription", comment: nil) }

      /// en translation: Others
      ///
      /// Key: feedBackIssuesRadio4
      ///
      /// Locales: en
      var feedBackIssuesRadio4: RswiftResources.StringResource { .init(key: "feedBackIssuesRadio4", tableName: "Localizables", source: source, developmentValue: "Others", comment: nil) }

      /// en translation: Please tell us more details or suggestions so that we can resolve your issue faster.
      ///
      /// Key: feedBackIssuesTextViewHint
      ///
      /// Locales: en
      var feedBackIssuesTextViewHint: RswiftResources.StringResource { .init(key: "feedBackIssuesTextViewHint", tableName: "Localizables", source: source, developmentValue: "Please tell us more details or suggestions so that we can resolve your issue faster.", comment: nil) }

      /// en translation: * Are you experiencing any issues？
      ///
      /// Key: feedBackIssuesTitle
      ///
      /// Locales: en
      var feedBackIssuesTitle: RswiftResources.StringResource { .init(key: "feedBackIssuesTitle", tableName: "Localizables", source: source, developmentValue: "* Are you experiencing any issues？", comment: nil) }

      /// en translation: Please select a issue type before submitting.
      ///
      /// Key: feedBackNeedCompleteCopy
      ///
      /// Locales: en
      var feedBackNeedCompleteCopy: RswiftResources.StringResource { .init(key: "feedBackNeedCompleteCopy", tableName: "Localizables", source: source, developmentValue: "Please select a issue type before submitting.", comment: nil) }

      /// en translation: Current content suits me well
      ///
      /// Key: feedBackQuestionnaireRadio1
      ///
      /// Locales: en
      var feedBackQuestionnaireRadio1: RswiftResources.StringResource { .init(key: "feedBackQuestionnaireRadio1", tableName: "Localizables", source: source, developmentValue: "Current content suits me well", comment: nil) }

      /// en translation: Cardio Workouts
      ///
      /// Key: feedBackQuestionnaireRadio2
      ///
      /// Locales: en
      var feedBackQuestionnaireRadio2: RswiftResources.StringResource { .init(key: "feedBackQuestionnaireRadio2", tableName: "Localizables", source: source, developmentValue: "Cardio Workouts", comment: nil) }

      /// en translation: Strength Training
      ///
      /// Key: feedBackQuestionnaireRadio3
      ///
      /// Locales: en
      var feedBackQuestionnaireRadio3: RswiftResources.StringResource { .init(key: "feedBackQuestionnaireRadio3", tableName: "Localizables", source: source, developmentValue: "Strength Training", comment: nil) }

      /// en translation: Relaxation & Recovery
      ///
      /// Key: feedBackQuestionnaireRadio4
      ///
      /// Locales: en
      var feedBackQuestionnaireRadio4: RswiftResources.StringResource { .init(key: "feedBackQuestionnaireRadio4", tableName: "Localizables", source: source, developmentValue: "Relaxation & Recovery", comment: nil) }

      /// en translation: Pilates/Yoga
      ///
      /// Key: feedBackQuestionnaireRadio5
      ///
      /// Locales: en
      var feedBackQuestionnaireRadio5: RswiftResources.StringResource { .init(key: "feedBackQuestionnaireRadio5", tableName: "Localizables", source: source, developmentValue: "Pilates/Yoga", comment: nil) }

      /// en translation: Quick Workouts (10-15 mins)
      ///
      /// Key: feedBackQuestionnaireRadio6
      ///
      /// Locales: en
      var feedBackQuestionnaireRadio6: RswiftResources.StringResource { .init(key: "feedBackQuestionnaireRadio6", tableName: "Localizables", source: source, developmentValue: "Quick Workouts (10-15 mins)", comment: nil) }

      /// en translation: Others
      ///
      /// Key: feedBackQuestionnaireRadio7
      ///
      /// Locales: en
      var feedBackQuestionnaireRadio7: RswiftResources.StringResource { .init(key: "feedBackQuestionnaireRadio7", tableName: "Localizables", source: source, developmentValue: "Others", comment: nil) }

      /// en translation: * What type of fitness content would you like to see more of？
      ///
      /// Key: feedBackQuestionnaireTitle
      ///
      /// Locales: en
      var feedBackQuestionnaireTitle: RswiftResources.StringResource { .init(key: "feedBackQuestionnaireTitle", tableName: "Localizables", source: source, developmentValue: "* What type of fitness content would you like to see more of？", comment: nil) }

      /// en translation: SUBMIT
      ///
      /// Key: feedBackSubmitTitle
      ///
      /// Locales: en
      var feedBackSubmitTitle: RswiftResources.StringResource { .init(key: "feedBackSubmitTitle", tableName: "Localizables", source: source, developmentValue: "SUBMIT", comment: nil) }

      /// en translation: Submit successfully. Thanks for your feedback！
      ///
      /// Key: feedBackSuccessCopy
      ///
      /// Locales: en
      var feedBackSuccessCopy: RswiftResources.StringResource { .init(key: "feedBackSuccessCopy", tableName: "Localizables", source: source, developmentValue: "Submit successfully. Thanks for your feedback！", comment: nil) }

      /// en translation: Contact Us
      ///
      /// Key: feedBackTitle
      ///
      /// Locales: en
      var feedBackTitle: RswiftResources.StringResource { .init(key: "feedBackTitle", tableName: "Localizables", source: source, developmentValue: "Contact Us", comment: nil) }
    }
  }

  /// This `_R.color` struct is generated, and contains static references to 3 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `backColor`.
    var backColor: RswiftResources.ColorResource { .init(name: "backColor", path: [], bundle: bundle) }

    /// Color `textColor`.
    var textColor: RswiftResources.ColorResource { .init(name: "textColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 123 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `AlbumAddBtn`.
    var albumAddBtn: RswiftResources.ImageResource { .init(name: "AlbumAddBtn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ArrowIcon`.
    var arrowIcon: RswiftResources.ImageResource { .init(name: "ArrowIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Bg`.
    var bg: RswiftResources.ImageResource { .init(name: "Bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `BlurIcon`.
    var blurIcon: RswiftResources.ImageResource { .init(name: "BlurIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `BoxIcon`.
    var boxIcon: RswiftResources.ImageResource { .init(name: "BoxIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Checkmark`.
    var checkmark: RswiftResources.ImageResource { .init(name: "Checkmark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `CloseButtonX`.
    var closeButtonX: RswiftResources.ImageResource { .init(name: "CloseButtonX", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_Auth_Instruct`.
    var ecg_Auth_Instruct: RswiftResources.ImageResource { .init(name: "ECG_Auth_Instruct", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_HeartRate_Icon`.
    var ecg_HeartRate_Icon: RswiftResources.ImageResource { .init(name: "ECG_HeartRate_Icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_Instruct`.
    var ecg_Instruct: RswiftResources.ImageResource { .init(name: "ECG_Instruct", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_Logo`.
    var ecg_Logo: RswiftResources.ImageResource { .init(name: "ECG_Logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_Watch`.
    var ecg_Watch: RswiftResources.ImageResource { .init(name: "ECG_Watch", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Photo_delete`.
    var photo_delete: RswiftResources.ImageResource { .init(name: "Photo_delete", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Pointer`.
    var pointer: RswiftResources.ImageResource { .init(name: "Pointer", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessCompleted`.
    var processCompleted: RswiftResources.ImageResource { .init(name: "ProcessCompleted", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessEdit`.
    var processEdit: RswiftResources.ImageResource { .init(name: "ProcessEdit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessInProgress`.
    var processInProgress: RswiftResources.ImageResource { .init(name: "ProcessInProgress", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessIncomplete`.
    var processIncomplete: RswiftResources.ImageResource { .init(name: "ProcessIncomplete", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessTips`.
    var processTips: RswiftResources.ImageResource { .init(name: "ProcessTips", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessWait`.
    var processWait: RswiftResources.ImageResource { .init(name: "ProcessWait", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `SpongeBob.gif`.
    var spongeBobGif: RswiftResources.ImageResource { .init(name: "SpongeBob.gif", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Van Gogh_Starry Night`.
    var vanGogh_StarryNight: RswiftResources.ImageResource { .init(name: "Van Gogh_Starry Night", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_1`.
    var weChat_Avatar_1: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_10`.
    var weChat_Avatar_10: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_10", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_11`.
    var weChat_Avatar_11: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_11", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_12`.
    var weChat_Avatar_12: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_12", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_13`.
    var weChat_Avatar_13: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_13", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_14`.
    var weChat_Avatar_14: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_14", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_15`.
    var weChat_Avatar_15: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_15", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_16`.
    var weChat_Avatar_16: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_16", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_17`.
    var weChat_Avatar_17: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_17", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_18`.
    var weChat_Avatar_18: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_18", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_19`.
    var weChat_Avatar_19: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_19", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_2`.
    var weChat_Avatar_2: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_20`.
    var weChat_Avatar_20: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_20", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_21`.
    var weChat_Avatar_21: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_21", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_22`.
    var weChat_Avatar_22: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_22", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_23`.
    var weChat_Avatar_23: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_23", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_24`.
    var weChat_Avatar_24: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_25`.
    var weChat_Avatar_25: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_25", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_26`.
    var weChat_Avatar_26: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_26", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_3`.
    var weChat_Avatar_3: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_4`.
    var weChat_Avatar_4: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_5`.
    var weChat_Avatar_5: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_6`.
    var weChat_Avatar_6: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_7`.
    var weChat_Avatar_7: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_8`.
    var weChat_Avatar_8: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_8", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_9`.
    var weChat_Avatar_9: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_9", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow`.
    var arrow: RswiftResources.ImageResource { .init(name: "arrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow_down`.
    var arrow_down: RswiftResources.ImageResource { .init(name: "arrow_down", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow_up`.
    var arrow_up: RswiftResources.ImageResource { .init(name: "arrow_up", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `batman`.
    var batman: RswiftResources.ImageResource { .init(name: "batman", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat`.
    var cat: RswiftResources.ImageResource { .init(name: "cat", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_list_add`.
    var chat_list_add: RswiftResources.ImageResource { .init(name: "chat_list_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_list_filter`.
    var chat_list_filter: RswiftResources.ImageResource { .init(name: "chat_list_filter", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_add`.
    var chat_tools_add: RswiftResources.ImageResource { .init(name: "chat_tools_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_photo`.
    var chat_tools_photo: RswiftResources.ImageResource { .init(name: "chat_tools_photo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_pic`.
    var chat_tools_pic: RswiftResources.ImageResource { .init(name: "chat_tools_pic", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_reply`.
    var chat_tools_reply: RswiftResources.ImageResource { .init(name: "chat_tools_reply", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_voice`.
    var chat_tools_voice: RswiftResources.ImageResource { .init(name: "chat_tools_voice", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `clock`.
    var clock: RswiftResources.ImageResource { .init(name: "clock", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_jrsy`.
    var cover_jrsy: RswiftResources.ImageResource { .init(name: "cover_jrsy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_lb`.
    var cover_lb: RswiftResources.ImageResource { .init(name: "cover_lb", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_md`.
    var cover_md: RswiftResources.ImageResource { .init(name: "cover_md", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_mfb`.
    var cover_mfb: RswiftResources.ImageResource { .init(name: "cover_mfb", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_rxg`.
    var cover_rxg: RswiftResources.ImageResource { .init(name: "cover_rxg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_szdsyyyt`.
    var cover_szdsyyyt: RswiftResources.ImageResource { .init(name: "cover_szdsyyyt", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_szqpz`.
    var cover_szqpz: RswiftResources.ImageResource { .init(name: "cover_szqpz", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_venereum`.
    var cover_venereum: RswiftResources.ImageResource { .init(name: "cover_venereum", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `default_avatar_100`.
    var default_avatar_100: RswiftResources.ImageResource { .init(name: "default_avatar_100", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `default_avatar_80`.
    var default_avatar_80: RswiftResources.ImageResource { .init(name: "default_avatar_80", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `drawOut`.
    var drawOut: RswiftResources.ImageResource { .init(name: "drawOut", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `edit_delete`.
    var edit_delete: RswiftResources.ImageResource { .init(name: "edit_delete", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `elephant`.
    var elephant: RswiftResources.ImageResource { .init(name: "elephant", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `feedback_back_icon`.
    var feedback_back_icon: RswiftResources.ImageResource { .init(name: "feedback_back_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `feedback_bg`.
    var feedback_bg: RswiftResources.ImageResource { .init(name: "feedback_bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `feedback_icon`.
    var feedback_icon: RswiftResources.ImageResource { .init(name: "feedback_icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift1`.
    var gift1: RswiftResources.ImageResource { .init(name: "gift1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift2`.
    var gift2: RswiftResources.ImageResource { .init(name: "gift2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift3`.
    var gift3: RswiftResources.ImageResource { .init(name: "gift3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift4`.
    var gift4: RswiftResources.ImageResource { .init(name: "gift4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift5`.
    var gift5: RswiftResources.ImageResource { .init(name: "gift5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift6`.
    var gift6: RswiftResources.ImageResource { .init(name: "gift6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift7`.
    var gift7: RswiftResources.ImageResource { .init(name: "gift7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `giftEmpty`.
    var giftEmpty: RswiftResources.ImageResource { .init(name: "giftEmpty", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_download`.
    var icon_download: RswiftResources.ImageResource { .init(name: "icon_download", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_plus`.
    var icon_plus: RswiftResources.ImageResource { .init(name: "icon_plus", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_read`.
    var icon_read: RswiftResources.ImageResource { .init(name: "icon_read", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_00`.
    var img_00: RswiftResources.ImageResource { .init(name: "img_00", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_01`.
    var img_01: RswiftResources.ImageResource { .init(name: "img_01", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_02`.
    var img_02: RswiftResources.ImageResource { .init(name: "img_02", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_03`.
    var img_03: RswiftResources.ImageResource { .init(name: "img_03", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_04`.
    var img_04: RswiftResources.ImageResource { .init(name: "img_04", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_05`.
    var img_05: RswiftResources.ImageResource { .init(name: "img_05", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `kermit`.
    var kermit: RswiftResources.ImageResource { .init(name: "kermit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `kt_sh`.
    var kt_sh: RswiftResources.ImageResource { .init(name: "kt_sh", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lattice`.
    var lattice: RswiftResources.ImageResource { .init(name: "lattice", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `loading.gif`.
    var loadingGif: RswiftResources.ImageResource { .init(name: "loading.gif", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `member_add`.
    var member_add: RswiftResources.ImageResource { .init(name: "member_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `monkey`.
    var monkey: RswiftResources.ImageResource { .init(name: "monkey", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `nav_back_black`.
    var nav_back_black: RswiftResources.ImageResource { .init(name: "nav_back_black", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `navigation_return_btn`.
    var navigation_return_btn: RswiftResources.ImageResource { .init(name: "navigation_return_btn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `option_radio_active`.
    var option_radio_active: RswiftResources.ImageResource { .init(name: "option_radio_active", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `option_radio_normal`.
    var option_radio_normal: RswiftResources.ImageResource { .init(name: "option_radio_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `placeholder`.
    var placeholder: RswiftResources.ImageResource { .init(name: "placeholder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rabbit`.
    var rabbit: RswiftResources.ImageResource { .init(name: "rabbit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `setting_add`.
    var setting_add: RswiftResources.ImageResource { .init(name: "setting_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_face_1`.
    var smile_face_1: RswiftResources.ImageResource { .init(name: "smile_face_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_face_2`.
    var smile_face_2: RswiftResources.ImageResource { .init(name: "smile_face_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_neutral`.
    var smile_neutral: RswiftResources.ImageResource { .init(name: "smile_neutral", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_rotten_1`.
    var smile_rotten_1: RswiftResources.ImageResource { .init(name: "smile_rotten_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_rotten_2`.
    var smile_rotten_2: RswiftResources.ImageResource { .init(name: "smile_rotten_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `star`.
    var star: RswiftResources.ImageResource { .init(name: "star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `start_button`.
    var start_button: RswiftResources.ImageResource { .init(name: "start_button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `stretchy_header`.
    var stretchy_header: RswiftResources.ImageResource { .init(name: "stretchy_header", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_me_normal`.
    var tab_me_normal: RswiftResources.ImageResource { .init(name: "tab_me_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_work_normal`.
    var tab_work_normal: RswiftResources.ImageResource { .init(name: "tab_work_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `turntableBg`.
    var turntableBg: RswiftResources.ImageResource { .init(name: "turntableBg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `voice1`.
    var voice1: RswiftResources.ImageResource { .init(name: "voice1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `voice2`.
    var voice2: RswiftResources.ImageResource { .init(name: "voice2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `voice3`.
    var voice3: RswiftResources.ImageResource { .init(name: "voice3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `主页_我的`.
    var 主页_我的: RswiftResources.ImageResource { .init(name: "主页_我的", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `对勾`.
    var 对勾: RswiftResources.ImageResource { .init(name: "对勾", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.info` struct is generated, and contains static references to 1 properties.
  struct info {
    let bundle: Foundation.Bundle
    var uiApplicationSceneManifest: uiApplicationSceneManifest { .init(bundle: bundle) }

    func uiApplicationSceneManifest(bundle: Foundation.Bundle) -> uiApplicationSceneManifest {
      .init(bundle: bundle)
    }

    struct uiApplicationSceneManifest {
      let bundle: Foundation.Bundle

      let uiApplicationSupportsMultipleScenes: Bool = false

      var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest"], key: "_key") ?? "UIApplicationSceneManifest" }
      var uiSceneConfigurations: uiSceneConfigurations { .init(bundle: bundle) }

      func uiSceneConfigurations(bundle: Foundation.Bundle) -> uiSceneConfigurations {
        .init(bundle: bundle)
      }

      struct uiSceneConfigurations {
        let bundle: Foundation.Bundle
        var _key: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations"], key: "_key") ?? "UISceneConfigurations" }
        var uiWindowSceneSessionRoleApplication: uiWindowSceneSessionRoleApplication { .init(bundle: bundle) }

        func uiWindowSceneSessionRoleApplication(bundle: Foundation.Bundle) -> uiWindowSceneSessionRoleApplication {
          .init(bundle: bundle)
        }

        struct uiWindowSceneSessionRoleApplication {
          let bundle: Foundation.Bundle
          var defaultConfiguration: defaultConfiguration { .init(bundle: bundle) }

          func defaultConfiguration(bundle: Foundation.Bundle) -> defaultConfiguration {
            .init(bundle: bundle)
          }

          struct defaultConfiguration {
            let bundle: Foundation.Bundle
            var uiSceneConfigurationName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneConfigurationName") ?? "Default Configuration" }
            var uiSceneDelegateClassName: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneDelegateClassName") ?? "$(PRODUCT_MODULE_NAME).SceneDelegate" }
            var uiSceneStoryboardFile: String { bundle.infoDictionaryString(path: ["UIApplicationSceneManifest", "UISceneConfigurations", "UIWindowSceneSessionRoleApplication"], key: "UISceneStoryboardFile") ?? "Main" }
          }
        }
      }
    }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 1 properties.
  struct entitlements {
    let comAppleDeveloperHealthkit: Bool = true
    let comAppleDeveloperHealthkitAccess = comAppleDeveloperHealthkitAccess()
    let comAppleDeveloperHealthkitBackgroundDelivery: Bool = true
    struct comAppleDeveloperHealthkitAccess {
      let healthRecords: String = "health-records"
    }
  }

  /// This `_R.font` struct is generated, and contains static references to 3 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `SourceSansPro-Bold`.
    var sourceSansProBold: RswiftResources.FontResource { .init(name: "SourceSansPro-Bold", bundle: bundle, filename: "SourceSansPro-Bold.ttf") }

    /// Font `SourceSansPro-Regular`.
    var sourceSansProRegular: RswiftResources.FontResource { .init(name: "SourceSansPro-Regular", bundle: bundle, filename: "SourceSansPro-Regular.ttf") }

    /// Font `SourceSansPro-Semibold`.
    var sourceSansProSemibold: RswiftResources.FontResource { .init(name: "SourceSansPro-Semibold", bundle: bundle, filename: "SourceSansPro-Semibold.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [sourceSansProBold, sourceSansProRegular, sourceSansProSemibold].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 14 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `SourceSansPro-Bold.ttf`.
    var sourceSansProBoldTtf: RswiftResources.FileResource { .init(name: "SourceSansPro-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SourceSansPro-Regular.ttf`.
    var sourceSansProRegularTtf: RswiftResources.FileResource { .init(name: "SourceSansPro-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SourceSansPro-Semibold.ttf`.
    var sourceSansProSemiboldTtf: RswiftResources.FileResource { .init(name: "SourceSansPro-Semibold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SpongeBob.gif`.
    var spongeBobGif: RswiftResources.FileResource { .init(name: "SpongeBob", pathExtension: "gif", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `ZhuoZhuo`.
    var zhuoZhuo: RswiftResources.FileResource { .init(name: "ZhuoZhuo", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `img_00.png`.
    var img_00Png: RswiftResources.FileResource { .init(name: "img_00", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `img_01.png`.
    var img_01Png: RswiftResources.FileResource { .init(name: "img_01", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `img_02.png`.
    var img_02Png: RswiftResources.FileResource { .init(name: "img_02", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `img_03.png`.
    var img_03Png: RswiftResources.FileResource { .init(name: "img_03", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `img_04.png`.
    var img_04Png: RswiftResources.FileResource { .init(name: "img_04", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `img_05.png`.
    var img_05Png: RswiftResources.FileResource { .init(name: "img_05", pathExtension: "png", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `loading.gif`.
    var loadingGif: RswiftResources.FileResource { .init(name: "loading", pathExtension: "gif", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `module.modulemap`.
    var moduleModulemap: RswiftResources.FileResource { .init(name: "module", pathExtension: "modulemap", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `userInfo.json`.
    var userInfoJson: RswiftResources.FileResource { .init(name: "userInfo", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 4 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `ConfigureView`.
    var configureView: RswiftResources.NibReference<ConfigureView> { .init(name: "ConfigureView", bundle: bundle) }

    /// Nib `ExpandableCell`.
    var expandableCell: RswiftResources.NibReferenceReuseIdentifier<ExpandableCell, ExpandableCell> { .init(name: "ExpandableCell", bundle: bundle, identifier: "cell") }

    /// Nib `ExpandableLabelVC`.
    var expandableLabelVC: RswiftResources.NibReference<UIKit.UIView> { .init(name: "ExpandableLabelVC", bundle: bundle) }

    /// Nib `PIViewController`.
    var piViewController: RswiftResources.NibReference<UIKit.UIView> { .init(name: "PIViewController", bundle: bundle) }

    func validate() throws {

    }
  }

  /// This `_R.reuseIdentifier` struct is generated, and contains static references to 1 reuse identifiers.
  struct reuseIdentifier {

    /// Reuse identifier `cell`.
    var cell: RswiftResources.ReuseIdentifier<ExpandableCell> { .init(identifier: "cell") }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 3 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var launchScreen: launchScreen { .init(bundle: bundle) }
    var main: main { .init(bundle: bundle) }
    var swiftAsciiArtVC: swiftAsciiArtVC { .init(bundle: bundle) }

    func launchScreen(bundle: Foundation.Bundle) -> launchScreen {
      .init(bundle: bundle)
    }
    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func swiftAsciiArtVC(bundle: Foundation.Bundle) -> swiftAsciiArtVC {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.launchScreen.validate()
      try self.main.validate()
      try self.swiftAsciiArtVC.validate()
    }


    /// Storyboard `Launch Screen`.
    struct launchScreen: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = UIKit.UIViewController

      let bundle: Foundation.Bundle

      let name = "Launch Screen"
      func validate() throws {

      }
    }

    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = MainTabbarController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {
        if #available(iOS 13.0, *) { if UIKit.UIImage(systemName: "pencil") == nil { throw RswiftResources.ValidationError("[R.swift] System image named 'pencil' is used in storyboard 'Main', but couldn't be loaded.") } }
      }
    }

    /// Storyboard `SwiftAsciiArtVC`.
    struct swiftAsciiArtVC: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "SwiftAsciiArtVC"

      var swiftAsciiArtVC: RswiftResources.StoryboardViewControllerIdentifier<SwiftAsciiArtVC> { .init(identifier: "SwiftAsciiArtVC", storyboard: name, bundle: bundle) }

      func validate() throws {
        if swiftAsciiArtVC() == nil { throw RswiftResources.ValidationError("[R.swift] ViewController with identifier 'swiftAsciiArtVC' could not be loaded from storyboard 'SwiftAsciiArtVC' as 'SwiftAsciiArtVC'.") }
      }
    }
  }
}