//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func validate() throws {

  }


  /// This `_R.color` struct is generated, and contains static references to 1 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 116 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `AlbumAddBtn`.
    var albumAddBtn: RswiftResources.ImageResource { .init(name: "AlbumAddBtn", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ArrowIcon`.
    var arrowIcon: RswiftResources.ImageResource { .init(name: "ArrowIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Bg`.
    var bg: RswiftResources.ImageResource { .init(name: "Bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `BlurIcon`.
    var blurIcon: RswiftResources.ImageResource { .init(name: "BlurIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `BoxIcon`.
    var boxIcon: RswiftResources.ImageResource { .init(name: "BoxIcon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Checkmark`.
    var checkmark: RswiftResources.ImageResource { .init(name: "Checkmark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `CloseButtonX`.
    var closeButtonX: RswiftResources.ImageResource { .init(name: "CloseButtonX", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_Auth_Instruct`.
    var ecg_Auth_Instruct: RswiftResources.ImageResource { .init(name: "ECG_Auth_Instruct", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_HeartRate_Icon`.
    var ecg_HeartRate_Icon: RswiftResources.ImageResource { .init(name: "ECG_HeartRate_Icon", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_Instruct`.
    var ecg_Instruct: RswiftResources.ImageResource { .init(name: "ECG_Instruct", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_Logo`.
    var ecg_Logo: RswiftResources.ImageResource { .init(name: "ECG_Logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ECG_Watch`.
    var ecg_Watch: RswiftResources.ImageResource { .init(name: "ECG_Watch", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Photo_delete`.
    var photo_delete: RswiftResources.ImageResource { .init(name: "Photo_delete", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Pointer`.
    var pointer: RswiftResources.ImageResource { .init(name: "Pointer", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessCompleted`.
    var processCompleted: RswiftResources.ImageResource { .init(name: "ProcessCompleted", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessEdit`.
    var processEdit: RswiftResources.ImageResource { .init(name: "ProcessEdit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessInProgress`.
    var processInProgress: RswiftResources.ImageResource { .init(name: "ProcessInProgress", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessIncomplete`.
    var processIncomplete: RswiftResources.ImageResource { .init(name: "ProcessIncomplete", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessTips`.
    var processTips: RswiftResources.ImageResource { .init(name: "ProcessTips", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ProcessWait`.
    var processWait: RswiftResources.ImageResource { .init(name: "ProcessWait", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `SpongeBob.gif`.
    var spongeBobGif: RswiftResources.ImageResource { .init(name: "SpongeBob.gif", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `Van Gogh_Starry Night`.
    var vanGogh_StarryNight: RswiftResources.ImageResource { .init(name: "Van Gogh_Starry Night", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_1`.
    var weChat_Avatar_1: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_10`.
    var weChat_Avatar_10: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_10", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_11`.
    var weChat_Avatar_11: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_11", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_12`.
    var weChat_Avatar_12: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_12", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_13`.
    var weChat_Avatar_13: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_13", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_14`.
    var weChat_Avatar_14: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_14", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_15`.
    var weChat_Avatar_15: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_15", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_16`.
    var weChat_Avatar_16: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_16", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_17`.
    var weChat_Avatar_17: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_17", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_18`.
    var weChat_Avatar_18: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_18", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_19`.
    var weChat_Avatar_19: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_19", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_2`.
    var weChat_Avatar_2: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_20`.
    var weChat_Avatar_20: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_20", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_21`.
    var weChat_Avatar_21: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_21", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_22`.
    var weChat_Avatar_22: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_22", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_23`.
    var weChat_Avatar_23: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_23", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_24`.
    var weChat_Avatar_24: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_24", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_25`.
    var weChat_Avatar_25: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_25", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_26`.
    var weChat_Avatar_26: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_26", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_3`.
    var weChat_Avatar_3: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_4`.
    var weChat_Avatar_4: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_5`.
    var weChat_Avatar_5: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_6`.
    var weChat_Avatar_6: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_7`.
    var weChat_Avatar_7: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_8`.
    var weChat_Avatar_8: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_8", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `WeChat_Avatar_9`.
    var weChat_Avatar_9: RswiftResources.ImageResource { .init(name: "WeChat_Avatar_9", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow`.
    var arrow: RswiftResources.ImageResource { .init(name: "arrow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow_down`.
    var arrow_down: RswiftResources.ImageResource { .init(name: "arrow_down", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow_up`.
    var arrow_up: RswiftResources.ImageResource { .init(name: "arrow_up", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cat`.
    var cat: RswiftResources.ImageResource { .init(name: "cat", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_list_add`.
    var chat_list_add: RswiftResources.ImageResource { .init(name: "chat_list_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_list_filter`.
    var chat_list_filter: RswiftResources.ImageResource { .init(name: "chat_list_filter", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_add`.
    var chat_tools_add: RswiftResources.ImageResource { .init(name: "chat_tools_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_photo`.
    var chat_tools_photo: RswiftResources.ImageResource { .init(name: "chat_tools_photo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_pic`.
    var chat_tools_pic: RswiftResources.ImageResource { .init(name: "chat_tools_pic", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_reply`.
    var chat_tools_reply: RswiftResources.ImageResource { .init(name: "chat_tools_reply", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chat_tools_voice`.
    var chat_tools_voice: RswiftResources.ImageResource { .init(name: "chat_tools_voice", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `clock`.
    var clock: RswiftResources.ImageResource { .init(name: "clock", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_jrsy`.
    var cover_jrsy: RswiftResources.ImageResource { .init(name: "cover_jrsy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_lb`.
    var cover_lb: RswiftResources.ImageResource { .init(name: "cover_lb", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_md`.
    var cover_md: RswiftResources.ImageResource { .init(name: "cover_md", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_mfb`.
    var cover_mfb: RswiftResources.ImageResource { .init(name: "cover_mfb", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_rxg`.
    var cover_rxg: RswiftResources.ImageResource { .init(name: "cover_rxg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_szdsyyyt`.
    var cover_szdsyyyt: RswiftResources.ImageResource { .init(name: "cover_szdsyyyt", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_szqpz`.
    var cover_szqpz: RswiftResources.ImageResource { .init(name: "cover_szqpz", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `cover_venereum`.
    var cover_venereum: RswiftResources.ImageResource { .init(name: "cover_venereum", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `default_avatar_100`.
    var default_avatar_100: RswiftResources.ImageResource { .init(name: "default_avatar_100", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `default_avatar_80`.
    var default_avatar_80: RswiftResources.ImageResource { .init(name: "default_avatar_80", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `drawOut`.
    var drawOut: RswiftResources.ImageResource { .init(name: "drawOut", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `edit_delete`.
    var edit_delete: RswiftResources.ImageResource { .init(name: "edit_delete", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `elephant`.
    var elephant: RswiftResources.ImageResource { .init(name: "elephant", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift1`.
    var gift1: RswiftResources.ImageResource { .init(name: "gift1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift2`.
    var gift2: RswiftResources.ImageResource { .init(name: "gift2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift3`.
    var gift3: RswiftResources.ImageResource { .init(name: "gift3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift4`.
    var gift4: RswiftResources.ImageResource { .init(name: "gift4", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift5`.
    var gift5: RswiftResources.ImageResource { .init(name: "gift5", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift6`.
    var gift6: RswiftResources.ImageResource { .init(name: "gift6", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `gift7`.
    var gift7: RswiftResources.ImageResource { .init(name: "gift7", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `giftEmpty`.
    var giftEmpty: RswiftResources.ImageResource { .init(name: "giftEmpty", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_download`.
    var icon_download: RswiftResources.ImageResource { .init(name: "icon_download", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_plus`.
    var icon_plus: RswiftResources.ImageResource { .init(name: "icon_plus", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_read`.
    var icon_read: RswiftResources.ImageResource { .init(name: "icon_read", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_00`.
    var img_00: RswiftResources.ImageResource { .init(name: "img_00", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_01`.
    var img_01: RswiftResources.ImageResource { .init(name: "img_01", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_02`.
    var img_02: RswiftResources.ImageResource { .init(name: "img_02", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_03`.
    var img_03: RswiftResources.ImageResource { .init(name: "img_03", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_04`.
    var img_04: RswiftResources.ImageResource { .init(name: "img_04", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `img_05`.
    var img_05: RswiftResources.ImageResource { .init(name: "img_05", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `kt_sh`.
    var kt_sh: RswiftResources.ImageResource { .init(name: "kt_sh", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `lattice`.
    var lattice: RswiftResources.ImageResource { .init(name: "lattice", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `loading.gif`.
    var loadingGif: RswiftResources.ImageResource { .init(name: "loading.gif", path: [], bundle: bundle, locale: LocaleReference.none, onDemandResourceTags: nil) }

    /// Image `member_add`.
    var member_add: RswiftResources.ImageResource { .init(name: "member_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `nav_back_black`.
    var nav_back_black: RswiftResources.ImageResource { .init(name: "nav_back_black", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `option_radio_active`.
    var option_radio_active: RswiftResources.ImageResource { .init(name: "option_radio_active", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `option_radio_normal`.
    var option_radio_normal: RswiftResources.ImageResource { .init(name: "option_radio_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `placeholder`.
    var placeholder: RswiftResources.ImageResource { .init(name: "placeholder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rabbit`.
    var rabbit: RswiftResources.ImageResource { .init(name: "rabbit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `setting_add`.
    var setting_add: RswiftResources.ImageResource { .init(name: "setting_add", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_face_1`.
    var smile_face_1: RswiftResources.ImageResource { .init(name: "smile_face_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_face_2`.
    var smile_face_2: RswiftResources.ImageResource { .init(name: "smile_face_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_neutral`.
    var smile_neutral: RswiftResources.ImageResource { .init(name: "smile_neutral", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_rotten_1`.
    var smile_rotten_1: RswiftResources.ImageResource { .init(name: "smile_rotten_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `smile_rotten_2`.
    var smile_rotten_2: RswiftResources.ImageResource { .init(name: "smile_rotten_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `star`.
    var star: RswiftResources.ImageResource { .init(name: "star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `start_button`.
    var start_button: RswiftResources.ImageResource { .init(name: "start_button", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `stretchy_header`.
    var stretchy_header: RswiftResources.ImageResource { .init(name: "stretchy_header", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_me_normal`.
    var tab_me_normal: RswiftResources.ImageResource { .init(name: "tab_me_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_work_normal`.
    var tab_work_normal: RswiftResources.ImageResource { .init(name: "tab_work_normal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `turntableBg`.
    var turntableBg: RswiftResources.ImageResource { .init(name: "turntableBg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `voice1`.
    var voice1: RswiftResources.ImageResource { .init(name: "voice1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `voice2`.
    var voice2: RswiftResources.ImageResource { .init(name: "voice2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `voice3`.
    var voice3: RswiftResources.ImageResource { .init(name: "voice3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `主页_我的`.
    var 主页_我的: RswiftResources.ImageResource { .init(name: "主页_我的", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `对勾`.
    var 对勾: RswiftResources.ImageResource { .init(name: "对勾", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }
}